### ISSUE TITLE
Option To Ignore Pull-Request Opener

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#290]
After implementing #286 the new default behaviour is to ignore approvals of the laster committer.

We could add a configurable option to additionally ignore pull-request openers.

How would this option look like? Would it be in the .zappr.yaml?

**Comment by prayerslayer** [comment]
~~~ yaml
approvals:
  ignore: [last_committer | pr_opener | none]
~~~

**Comment by prayerslayer** [comment]
Or maybe `nobody` feels more natural than `none`?

**Comment by ePaul** [comment]
I guess for a four-eyes principle I need at least two people agreeing. If the PR-opener is the same person as the author of all the commits (or maybe at least, all the commits added after opening the PR, if this can be distinguished), one :+1: from someone else should be enough (assuming the PR author is implicitly approving his own stuff). Otherwise, we should have two :+1: from two different people, even if one of them is the PR author or one of the committers. Adding a commit on someone else's commit doesn't mean I'm approving those commits, IMHO.

**Comment by mfellner** [comment]
@ePaul how about a rule, that we need at least one approval from somebody who didn't commit?

What happens in the case of everybody committing? This is especially likely on very small projects with just two or three developers.

**Comment by ePaul** [comment]
My idea would be that if several people commit, at least two of them (or one of them and one other person, or two other persons) need to approve the whole result (after the last commit), thereby confirming that they don't just like their own commits, but also the whole pull request's changes.

(Of course, I'm aware that this is not for all teams, but I would like to try it in my team.)

**Comment by prayerslayer** [comment]
>  Adding a commit on someone else's commit doesn't mean I'm approving those commits, IMHO.

Because you did (or did not) modify changes from others that came before your commit, you implicitly approve those. I'd say that assumption holds up.

**Comment by ePaul** [comment]
When I go through a lengthy diff, I sometimes fix minor issues which come up during the review, and commit them. This doesn't mean that there are no other issues which might need to be discussed.

**Comment by prayerslayer** [comment]
> This doesn't mean that there are no other issues which might need to be discussed.

Then why approve the PR? 😄

**Comment by ePaul** [comment]
> Then why approve the PR?

I'm *not* approving, that is the point. To make it clear, the scenario is this one:

1. Alice makes several changes on a feature branch and opens a pull request.
2. Paul reviews the pull request, notes a big mistake in comments, and fixes another minor mistake by adding a commit.
3. Alice approves after Paul's commit, although the mistakes noted by me are not resolved.
4. Due to the behavior of just ignoring the last committer, the PR can now be merged.

Or alternatively this one:

1. Alice makes several changes on a feature branch and opens a pull request.
2. Paul starts reviewing the pull request (but didn't finish because it is so large) and fixes a minor mistake by adding a commit. Another large mistake was not yet discovered because it is in a file way down there.
3. Alice approves after Paul's commit.
4. Due to the behavior of just ignoring the last committer, the PR can now be merged (while most of the code wasn't even looked at).

In these case I would like to have both Paul and Alice (or any other two allowed approvers) approve.

Of course you can make a rule like "only add commits if you think all the previous commits are good", but if the previous commits are good, why would you need more commits?

**Comment by prayerslayer** [comment]
Both of your scenarios would be fixed by configuring two approvers instead of one. Then you have a problem when you're only two people working on this project, but you can configure `ignore: none` to count all approvals.

**Comment by ePaul** [comment]
Yes, having always the PR opener approve his own PR would work too.

I just liked to have the shortcut of needing just one non-Alice approve if all the commits (or maybe only all the commits after opening the PR, if that is possible) are from Alice (who opened the PR).
