### ISSUE TITLE
One-click deployment

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#325]
According to GitHub, a large number of users are using private repositories. In order not to have to deal with sensitive user data, an alternative would be to provide simple options for **one-click deployment.** That way, businesses and other users could easily run their own Zappr instance.

- [ ] [Heroku](https://devcenter.heroku.com/articles/heroku-button) button
- [ ] [Azure](https://azure.microsoft.com/en-us/blog/deploy-to-azure-button-for-azure-websites-2) button
- [ ] Docker image on [Docker Hub](https://hub.docker.com)

**Comment by prayerslayer** [comment]
For this we have to support private repositories in the first place, which we currently do not.

**Comment by mfellner** [comment]
At least this would make it easy to use for people who run their own GitHub Enterprise instances as well.

**Comment by prayerslayer** [comment]
Agreed. They would have to use our default config then or am I missing something?

**Comment by prayerslayer** [comment]
Looked into this a bit deeper and I don't think we can do this. Spinning up servers and databases with a button click is all fine and dandy, but it mainly won't work due to the OAuth application needed. (Client ID + Client secret + redirect URL must match when you sign in.)

Since doing additional stuff kind of defeats the purpose of a One Click Deployment and we presumably cannot pass existing secrets to the deployment, I suppose everyone is better off when we put effort into:

* [Run your own](http://zappr.readthedocs.io/en/latest/run-your-own/) docs
* Database migration story (will open an issue for that)
* Providing a basic Zappr image on Docker Hub, where you only need to add the configuration layer
