### ISSUE TITLE
Delete GitHub data once we lose access

### ISSUE THREAD

**Issue by mfellner** [zalando/zappr#329]
We should delete any [user data](https://developer.github.com/integrations-directory/getting-listed/#delete-github-data-once-you-lose-access-to-the-information) within 60 days of losing access to it.

This would mean adding some sort of periodic task that automatically removes users, repositories etc. that are no longer available through the API (either because they were deleted on GitHub or because the access token is invalid).

**Comment by prayerslayer** [comment]
We could build this into Zappr itself (not preferred) or write a cleanup job. If we go for the latter, cleaner solution, we most probably need some kind of service user API access (e.g. authentication via Oauth instead of cookies).

**Comment by prayerslayer** [comment]
The GitHub docs state:

> Once you realize you've lost access to a user, organization, repository, or its related objects, delete that information in your system within 60 days.

I'm wondering how to find this out.

* **Lost access to user** I would have said we check the stored access token for validity, but there is none. We could use the time since last login as a proxy and delete users we haven't seen for a year.
* **Lost access to organization** We don't store any organization data.
* **Lost access to repository** This is a tricky one. I'd say any of the following:
  * No users in database are related to a repository.
  * Repository has checks enabled, but none of the stored access tokens works for it anymore.

**Comment by prayerslayer** [comment]
Done, Job deletes

* Users which did not sign in for a year
* Repositories that do not belong to any user

I would like to change this to

* deleting repos with checks that did not execute for <REASONABLE INTERVAL>
* users without repositories

But it's good enough for now.
