### ISSUE TITLE
Support multiline commit messages

### ISSUE THREAD

**Issue by prayerslayer** [zalando/zappr#341]
Currently we create a new `RegExp` without any modifiers, which causes a commit message like

~~~
feat(docs): foo foo

#123 awesome
~~~

to fail as the ticket id is not on the first line.

### Needed

- [ ] CommitMessage check uses multiline Regex
- [ ] Tests for it

**Comment by avaczi** [comment]
+1

**Comment by slitsche** [comment]
+1
I like the git convention which says that first commit message should not exceed certain amount of characters. Therefore we like to use multiple lines.
Furthermore I like to have a clean commit history in order to get an fast overview what happened. For this ticket numbers are secondary. I prefer to have them in the body of a commit message.

**Comment by christianberg** [comment]
I would also like to see support for putting ticket IDs anywhere in the commit message.

Even more importantly, the current regex only searches for ticket IDs at the beginning of the line. If you write your commit messages in an editor (instead of using `git commit -m "message"`, all lines starting with `#` are ignored, so it's (almost) impossible to put ticket IDs into the message.

(There's a workaround by customizing the comment character used by git, but it's a hassle.)

**Comment by mtrovo** [comment]
+1 
Also amending commit messages when you have several commits on the same branch with the same problem is really hard because you cannot easily put a `#` on the beginning of a commit message without messing with git configs, as @christianberg pointed.

**Comment by prayerslayer** [comment]
Alright, let's see when I get to this.

**Comment by jbspeakr** [comment]
just ran into exactly that problem... looking forward to see this in the next version!
