### ISSUE TITLE
Automatically add links to issues/tickets

### ISSUE THREAD

**Issue by fragsalat** [zalando/zappr#395]
For the new approval flow via Github the specification check is required. These requires a minimum body length of 8 and available links to specifications per default. To reduce the pain of grabbing the links to the related issues / tickets a new check would be a good solution. The check should iterate over all commits within the pull request and parse the ticket id's with a configurable pattern. For all issues there should be appended a unique link to the pull request body. This check should run before the specification check since it changes the body and makes the pr compliant.

**Comment by prayerslayer** [comment]
I like and appreciate that you want to automate a manual task you have 👏 However I also have some concerns.

First of all, this feature only works if you put ticket references in your commit messages, which is not required or enforced anywhere. One can also work almost without tickets by putting the spec (directly or a link) into the PR description.

Secondly I have to question the "pain of grabbing the links to the related issues". I agree it's painful if you regularly have pull requests that

1. contain multiple tickets,
2. that are managed by an external issue tracker (ie not Github).

As for 1. I think this is not good practice, a pull request should concern only one thing. As for 2. I think it kind of contradicts one of the primary goals of Zappr, to support you in doing all your work **with Github**.

Thirdly I don't think this should be a separate check, as it would introduce a dependency between them. If anything this should be a sub-feature of the `specification` check.

Overall I feel this would be a solution to a very specific problem and not affect the majority of Zappr users.

**Comment by fragsalat** [comment]
At first thx for your response :)

Some your concerns I can share but for me there is still a valid reason to have this feature.
This feature requires a self defined convention to work. This convention could be enforced by  https://github.com/zalando/zappr/blob/master/server/checks/CommitMessage.js to ensure that a issue/ticket number is added to the commit.
I as a user of zappr would say that zappr is not to help only with github but with the general workflow, which includes also issue trackers like jira or pivotal tracker. Everyone who comes from Bitbucket or Stash to Github will miss the feature of linked tickets. It can be very annoying to grab the ticket number, open your tracker and search for the issue to know what the feature the pr implements is about or to proceed in the ticket flow. I also created the feature so generic that it can make sense if you only use Github.

The integration into an another check like specification would be an option and would also reduce some load and requests. If you would appreciate this more I can implement it as an optional configuration.

Best
Thomas

**Comment by bootstraponline** [comment]
I think a feature like this is best implemented as a new project. Zappr is not an integration tool for 3rd party issue trackers.

For JIRA, there's a `JIRA DVCS plugin`

> https://help.github.com/articles/integrating-jira-with-your-projects/

**Comment by prayerslayer** [comment]
> I as a user of zappr would say that zappr is not to help only with github but with the general workflow.

But as a developer of Zappr I have to tell you that we care about Github only and don't see integrating 3rd party tools as part of our job. We want to improve the development workflow with Github, on Github. If we see something that is considered useful in other tools, we evaluate if and how we can build it with Github's tools.

>  Everyone who comes from Bitbucket or Stash to Github will miss the feature of linked tickets. It can be very annoying to grab the ticket number, open your tracker and search for the issue to know what the feature the pr implements is about or to proceed in the ticket flow. I also created the feature so generic that it can make sense if you only use Github.

Maybe I misunderstood you. I thought your issue is about automatically passing our `specification` check. 😏 If, however, your actual pain point is that there is no easy way to get from PR to specification when using a 3rd party issue tracker together with Github, then I'm afraid we won't fix that. Github issues mentioned in commits and comments are already automatically linked in the web UI, so for users of Github issues there is almost no benefit of implementing your solution.

> For JIRA, there's a JIRA DVCS plugin

But I think this only updates data in JIRA and not the Github PR? Also it's [deprecated](https://marketplace.atlassian.com/plugins/com.atlassian.jira.plugins.jira-bitbucket-connector-plugin/versions) and built into JIRA.

I agree however that the proposed functionality would best be part of that and not Zappr.

**Comment by prayerslayer** [comment]
Any further comments on this? I'll close this issue and the accompanying PR otherwise 😞
