### ISSUE TITLE
My organizations' repos don't show until I've pushed "sync with GitHub"

### ISSUE THREAD

**Issue by akauppi** [zalando/zappr#484]
Getting started with Zappr, I initially didn't get more than my own (`akauppi`) repos visible in the tool. Signed out and back in, spent some hours with this... until I came to press the `sync with GitHub` button. Seems that was needed to get visibility to the repo I wanted to attach to.

Steps:
- Setting up Zappr for the first time
- Following the [instructions](https://techwiki.zalando.net/pages/viewpage.action?pageId=29892050#expand-GithubApprovalflowUserGuideifyougetamailbyITComplianceonly) (internal Zalando link).
- Opening [https://zappr.bus.zalan.do/login](https://zappr.bus.zalan.do/login)

Expected:
- All repos I'm owner of should be listed, in the left

Actual:
- Only my own, personal accounts' repos/forks were listed

Setup:
- macOS, Chrome 56

**Comment by prayerslayer** [comment]
I'm afraid I won't fix this, let me explain why:

After Github redirected you back to Zappr, its frontend requests your repos from the Zappr backend. As you signed in for the first time, there aren't any. Now we have several options:

* Fetcb only first page of your repos from GH initially, do full sync after manual trigger (current situation). They are sorted by full name (`foo/bar`), which is why only personal repos appear in your case.
* Fetch all your repos at once. This just takes too long.
* Fetch all pages one after the other. This clogs the event loop with callbacks when there are many pages.

The proper solution would be some combination of diffing and pushed updates from the backend (maybe with websockets), but for that I don't have the resources. Happy to help on a PR though.

**Comment by akauppi** [comment]
I came to the mention about syncing in the docs, eventually, and I understand in my case this was even more confusing, since my personal repos were the first ones fetched, for alphabetical reasons.

I acknowledge the "will just take too long" argument. However, there are also some other options:

- the list or number of repositories in Zappr could indicate that the count is not final. Now it showed "30" and no indication at the end of the list (I think), which are clear indications to me as a user that that's all the tool knows about. So I was looking for reasons elsewhere. Marking something like "Repositories (please press sync)" would do the trick. I ended up having 230.

or

- Making the sync if one places focus in the search field. That was my primary instinct, I think, trying to search for more. Which didn't show any matches.

Just my 2c. Zappr seems easy to use, apart of my getting started problem. Thanks!

And also thanks for a good cause description, @prayerslayer

**Comment by prayerslayer** [comment]
> the list or number of repositories in Zappr could indicate that the count is not final

That's a good point and more easy solution. Judging from the GitHub docs there's no way to get an exact count of all repos, but we could do a back-of-the-envelope calculation with `pages * page size`. So the list would show "30 / ~250".

**Comment by akauppi** [comment]
or `30 (sync for more)`?

**Comment by prayerslayer** [comment]
Also possible, but then we would need to be reasonably sure that there are actually more repos upstream :)

**Comment by mawenzel** [comment]
Cleaned up during backlog grooming
