### ISSUE TITLE
Support for Tasks in Comments

### ISSUE THREAD

**Issue by winterDroid** [zalando/zappr#525]
It would be great if the TaskCheck would also honor tasks in comments and not just in the description.

**Comment by lotharschulz** [comment]
Thanks for your contribution. Please elaborate on why tasks in comments are great for you. As of now we do not plan to work on such a feature, so PRs are welcome.

**Comment by winterDroid** [comment]
It would make it possible to enforce violation fixes (e.g. posted by [this](https://github.com/tomasbjerre/violation-comments-to-github-gradle-plugin)) in a rather simple way

**Comment by lotharschulz** [comment]
I see. Since this won't change plans most likely can you try to use 👎 or `-1` as workaround.

As an example:
https://github.com/zalando/zappr/blob/master/.zappr.yaml effective configuration contains:

```
....
  veto:
    pattern: "^(:\\-1:|👎)$"
....
```

Can the [plugin](https://github.com/tomasbjerre/violation-comments-to-github-gradle-plugin) post comments as defined in the pattern above?
